configracion:
  mensaje: Configurando microservicio recarga dev

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/db_recarga
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

